package com.application.covid19.states

class States {
    fun getStatesMap(): Map<String, String> {
        return mapOf(
            "Alabama" to "AL",
            "Alaska" to "AK",
            "Arkansas" to "AR",
            "Arizona" to "AZ",
            "California" to "CA",
            "Colorado" to "CO",
            "Connecticut" to "CT",
            "Delaware" to "DE",
            "Florida" to "FL",
            "Georgia" to "GA",
            "Hawaii" to "HI",
            "Iowa" to "IA",
            "Idaho" to "ID",
            "Illinois" to "IL",
            "Indiana" to "IN",
            "Kansas" to "KS",
            "Kentucky" to "KY",
            "Louisiana" to "LA",
            "Massachusetts" to "MA",
            "Maryland" to "MD",
            "Maine" to "ME",
            "Michigan" to "MI",
            "Minnesota" to "MN",
            "Missouri" to "MO",
            "Mississippi" to "MS",
            "Montana" to "MT",
            "North Carolina" to "NC",
            "North Dakota" to "ND",
            "Nebraska" to "NE",
            "New Hampshire" to "NH",
            "New Jersey" to "NJ",
            "New Mexico" to "NM",
            "Nevada" to "NV",
            "New York" to "NY",
            "Ohio" to "OH",
            "Oklahoma" to "OK",
            "Oregon" to "OR",
            "Pennsylvania" to "PA",
            "Rhode Island" to "RI",
            "South Carolina" to "SC",
            "South Dakota" to "SD",
            "Tennessee" to "TN",
            "Texas" to "TX",
            "Utah" to "UT",
            "Virginia" to "VA",
            "Vermont" to "VT",
            "Washington" to "WA",
            "Wisconsin" to "WI",
            "West Virginia" to "WV",
            "Wyoming" to "WY",
        )
    }
}
